sanidart_rails_ver00/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'home#index'
  
  get 'works', to: 'home#index'
    
  resources :profiles
  
  resources :pages
  
  resources :posts

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

sanidart_rails_ver00/app/views/layouts/_footer.html.erb
<nav class="navbar navbar-dark bg-light-custom">
  <div class="container-fluid">
        <a class="nav-link ms-auto" href="https://hencan.github.io/portfolio/" target="_blank">
          <div class="logo-hencan" style="width:25px; height:25px;"></div>
        </a>
  </div>
</nav>

sanidart_rails_ver00/app/views/layouts/_header.html.erb
<nav id="navbar" class="navbar sticky-top navbar-expand-lg navbar-light bg-light-custom shadow-sm" style="z-index: 1000;">
  <div class="container-fluid">
    <% if Profile.where(main: true).exists? %>
      <%= link_to root_path, class:"navbar-brand mb-1 text-dark fs-2", style:"font-family: 'Ma Shan Zheng', cursive;" do %>
        <i id="logo" class="bi bi-flower1 fw-bold me-2"></i><%= Profile.where(main: true)[0].name %>
      <% end %>
    <% else %>
      <%= link_to root_path, class:"navbar-brand fs-2", style:"font-family: 'Ma Shan Zheng', cursive;" do %>
        <i id="logo"  class="bi bi-outlet me-2"></i>"C-3PO"
      <% end %>
    <% end %>
    <button class="navbar-toggler text-dark border-0" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation" onclick="this.blur()">
      <%# <span class="navbar-toggler-icon"></span> %>
      <svg xmlns="http://www.w3.org/2000/svg" class="mx-auto" viewBox="0 0 24 24" fill="#000000e6" width="25px" height="25px"><path d="M0 0h24v24H0z" fill="none"/><path d="M4 8h4V4H4v4zm6 12h4v-4h-4v4zm-6 0h4v-4H4v4zm0-6h4v-4H4v4zm6 0h4v-4h-4v4zm6-10v4h4V4h-4zm-6 4h4V4h-4v4zm6 6h4v-4h-4v4zm0 6h4v-4h-4v4z"/></svg>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a id="goto_top" class="nav-link text-dark ms-2" onclick="window.scrollTo(0, 0)" style="cursor:pointer;">Início</a>
          <%#= link_to "Início" , root_path, class:"nav-link fw-bold active" %>
        </li>
        <li class="nav-item">
          <a id="goto_work_btn" class="nav-link text-dark ms-2" style="cursor: pointer;" onclick="getElementById('works_area').scrollIntoView({block: 'start', behavior: 'smooth'});">Trabalhos</a>
        </li>
        <li class="nav-item">
          <%= link_to "Entrar em Contato" , root_path, class:"nav-link text-dark ms-2" %>
        </li>
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0 me-2">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link text-dark dropdown-toggle ms-2 align-middle" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
              <i class="bi bi-person-circle fs-5 me-1"></i><%= current_user.first_name %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "Editar Conta" , edit_user_registration_path, class:"dropdown-item" %></li>
              <li><a class="dropdown-item disabled" aria-disabled="true">Mesnsagens</a></li>
              <li><a class="dropdown-item disabled" aria-disabled="true">Favoritos</a></li>
              <% if current_user.admin %>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "Customizar" , profiles_path, class:"dropdown-item" %></li>
                <li><%= link_to "Páginas" , pages_path, class:"dropdown-item" %></li>
                <li><%= link_to "Posts" , posts_path, class:"dropdown-item" %></li>
                <li><%= link_to "Admin" , rails_admin_path, class:"dropdown-item" %></li>
              <% end %>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class:"btn btn-outline-danger btn-sm fw-bold rounded-pill m-2" do %>
              <span class="mx-3">Sair</span>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to new_user_session_path, method: :get, class:"btn  btn-outline-light text-dark border-dark btn-sm fw-bold rounded-pill m-2" do %>
              <span class="mx-3">Fazer login</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_registration_path, method: :get, class:"btn btn-primary btn-sm fw-bold rounded-pill m-2" do %>
              <span class="mx-3">Inscrever-se</span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<%# <div id="navbar_space" class="bg-transp" style="width:100%; height:30px;"></div> %>
<script>
  // setInterval(function(){document.getElementById("logo").style.color = "#" + Math.floor(Math.random()*16777215).toString(16);}, 10000);
</script>

sanidart_rails_ver00/app/views/layouts/_notice.html.erb
<div class="container-fluid position-fixed bottom-0 start-0" style="z-index:1100;">
  <div class="alert alert-primary text-dark border-dark alert-dismissible fade show my-3" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
</div>

sanidart_rails_ver00/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SanidartRailsServer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous"> %>
    <%# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script> %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">

    <%# <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script> %>
    <%# <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script> %>

    <style>
      @import url('https://fonts.googleapis.com/css2?family=Ma+Shan+Zheng&display=swap');
    </style>
    
  </head>

  <body>

    <%= render 'layouts/header' %>

    <% if notice %>
      <%= render 'layouts/notice' %>
    <% end %>

    <div>
      <%= yield %>
    </div>

  </body>
</html>