sanidart_rails_ver00/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'home#index'
  
  get 'works', to: 'home#index'
    
  resources :profiles
  
  resources :pages
  
  resources :posts

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

sanidart_rails_ver00/app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    
    @profiles_export = Profile.where(main: true).limit(1)

    @pages_export = Page.where(visible: true)    

    # Favorite.where(fav_user: current_user.id, fav_id: it["id"]).exists?
    @works = Post.search_with(params).paginate(page: params[:page], per_page: 20)

  end

end

sanidart_rails_ver00/app/helpers/home_helper.rb
module HomeHelper
end

sanidart_rails_ver00/app/views/home/_results.html.erb
<% if @works.exists? %>
  <div class="container-fluid pb-5">
    <div class="row grid_masonry">
      <% @works.each do |post| %>
        <div class="col-md-6 col-xl-4 mb-4">
          <div class="card bg-dark text-white" data-bs-toggle="modal" data-bs-target="#show_post_<%= post.id %>" style="cursor:pointer;">
            <% if post.image.nil? %>
              <svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="200" viewBox="0 0 24 24" width="200" class="card-img"><g><rect fill="none" height="24" width="24"/><path d="M21.9,21.9l-8.49-8.49l0,0L3.59,3.59l0,0L2.1,2.1L0.69,3.51L3,5.83V19c0,1.1,0.9,2,2,2h13.17l2.31,2.31L21.9,21.9z M5,18 l3.5-4.5l2.5,3.01L12.17,15l3,3H5z M21,18.17L5.83,3H19c1.1,0,2,0.9,2,2V18.17z"/></g></svg>
            <% else %>
              <%= image_tag(post.image, class: "card-img") %>
            <% end %>
            <div class="custom-overlay bg-middle-3">
              <div class="card-title fs-6"><%= post.title %></div>
              <p class="card-text ellipsis fs-6 mb-3"><%= post.subtitle %></p>
              <div class="card-text d-flex justify-content-between">
                <span class="fs-6"><i class="bi bi-eye me-2"></i>20</span>
                <span class="fs-6">10<i class="bi bi-stars ms-2"></i></span>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <div class="text-muted"><%= will_paginate @works, class:"digg_pagination" %></div>
    </div>
    <% @works.each do |full_post| %>
      <div class="modal fade show" id="show_post_<%= full_post.id %>" tabindex="-1" aria-labelledby="exampleModalXlLabel"
        style="display: none;" aria-modal="true" role="dialog">
        <div class="modal-dialog modal-fullscreen modal-dialog-scrollable">
          <div class="modal-content">
            <div class="modal-header d-flex flex-column border-bottom-0 shadow-sm">
              <div class="d-flex flex-row w-100">
                <% if full_post.image.nil? %>
                  <svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="40" viewBox="0 0 24 24" width="40"><g><rect fill="none" height="24" width="24"/><path d="M21.9,21.9l-8.49-8.49l0,0L3.59,3.59l0,0L2.1,2.1L0.69,3.51L3,5.83V19c0,1.1,0.9,2,2,2h13.17l2.31,2.31L21.9,21.9z M5,18 l3.5-4.5l2.5,3.01L12.17,15l3,3H5z M21,18.17L5.83,3H19c1.1,0,2,0.9,2,2V18.17z"/></g></svg>
                <% else %>
                  <%= image_tag(full_post.image, class:"img-thumbnail me-2", size: "40x40") %>
                <% end %>
                <span class="d-flex align-items-center fw-bold fs-3"><%= full_post.title %></span>
                <div class="ms-auto">
                  <button type="button" class="btn" style="padding: 0; margin:0;" data-bs-dismiss="modal">
                    <svg height="20" width="20" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="times" class="svg-inline--fa fa-times fa-w-11" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 352 512"><path fill="currentColor" d="M242.72 256l100.07-100.07c12.28-12.28 12.28-32.19 0-44.48l-22.24-22.24c-12.28-12.28-32.19-12.28-44.48 0L176 189.28 75.93 89.21c-12.28-12.28-32.19-12.28-44.48 0L9.21 111.45c-12.28 12.28-12.28 32.19 0 44.48L109.28 256 9.21 356.07c-12.28 12.28-12.28 32.19 0 44.48l22.24 22.24c12.28 12.28 32.2 12.28 44.48 0L176 322.72l100.07 100.07c12.28 12.28 32.2 12.28 44.48 0l22.24-22.24c12.28-12.28 12.28-32.19 0-44.48L242.72 256z"></path></svg>
                  </button>
                </div>
              </div>
              <div class="d-flex flex-row w-100 mt-1">
                <button type="button" class="btn btn-outline-dark border-0 " data-bs-toggle="tooltip" data-bs-placement="top" title="Dar estrela"><i class="bi bi-star-fill"></i></button>
                <button type="button" class="btn btn-outline-dark border-0 ms-2" data-bs-toggle="tooltip" data-bs-placement="top" title="Compartilhar"><i class="bi bi-share-fill"></i></button>
                <div class="ms-auto">                
                  <div class="btn-group">
                    <button class="btn btn-success" type="button">Encomendar</button>
                    <button type="button" class="btn btn-success dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                      <span class="visually-hidden">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item">Mensagem</a></li>
                      <li><a class="dropdown-item">Whatsapp</a></li>
                      <li><a class="dropdown-item">Telegram</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div class="modal-body">
              <div class="container-fluid">
                <div class="row">
                  <div class="ql-editor modals"><%= full_post.content %></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="container-fluid pb-5">
    <h2 class="m-4">Nada por aqui, por favor consulte mais tarde. :)</h2>
  </div>
<% end %>
<script>
  function rich_text_replace_terms() {
      var elements = document.querySelectorAll(".modals")
  
      for (var i=0; i < elements.length; i++) {
        elements[i].innerHTML = elements[i].innerHTML.replace(/&lt;/g, "<").replace(/&gt;/g, ">")
      }
    }
  
    rich_text_replace_terms()
</script>

sanidart_rails_ver00/app/views/home/_works.html.erb
<div class="sticky-top" id="works_area" style="z-index: 900;">
  <nav class="navbar navbar-expand-lg bg-light-custom mt-5">
    <div class="container-fluid">
      <span class="navbar-brand mb-3 text-dark fs-4 fw-bold"><i class="bi bi-grid-1x2-fill me-2"></i>Trabalhos</span>
    </div>
  </nav>
  <nav class="navbar navbar-expand-lg navbar-light bg-light-custom shadow-sm">
    <div class="container-fluid">
      <div class="d-flex align-items-center w-100" id="navbarSupportedContent2">
        <% if @works.exists? %>
          <%= form_tag works_path, :method => "get", :remote => true, :id => "works_filters", :style => "width: 100%;" do %>
            <div class="row mt-2">
              <div class="col-sm-6 mb-2">
                <div class="input-group">
                  <span class="input-group-text bg-dark text-light" style="border-radius: 50rem 0 0 50rem !important;"><i class="bi bi-search"></i></span>
                  <%= text_field_tag :with_title, params[:with_title], class: "form-control", style:"border-radius: 0 50rem 50rem 0 !important;", placeholder: "Pesquisar título" %>
                </div>
              </div>
              <div class="col-sm-4 mb-2">
                <% category_array = Post.all.map { |post| [post.category, post.category] } %>
                <% category_array = category_array.uniq %>
                <% category_array.unshift(["Todos", ""]) %>
                <div class="input-group">
                  <span class="input-group-text bg-dark text-light" style="border-radius: 50rem 0 0 50rem !important;"><i class="bi bi-tags me-2"></i>Categorias</span>
                  <%= select_tag :with_category, options_for_select(category_array, ""), class: "form-select rounded-pill", style:"border-radius: 0 50rem 50rem 0 !important;" %>
                </div>
              </div>
              <div class="col-sm-2 mb-2 justify-content-md-end">
                <div class="d-grid">
                  <%= submit_tag "Filtrar", :name => nil, class:"btn btn-dark rounded-pill", id:"works_submit" %>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <%= form_tag works_path, :method => "get", :remote => true, :id => "works_filters", :style => "width: 100%;" do %>
            <div class="row mt-2">
              <div class="col-sm-6 mb-2">
                <div class="input-group">
                  <span class="input-group-text bg-dark text-light"><i class="bi bi-search"></i></span>
                  <%= text_field_tag :with_title, params[:with_title], class: "form-control", placeholder: "Pesquisar título", disabled: true %>
                </div>
              </div>
              <div class="col-sm-4 mb-2">
                <% category_array = [] %>
                <% category_array.push(["Todos", ""]) %>
                <div class="input-group">
                  <span class="input-group-text bg-dark text-light"><i class="bi bi-tags me-2"></i>Categorias</span>
                  <%= select_tag :with_category, options_for_select(category_array, ""), class: "form-select", disabled: true %>
                </div>
              </div>
              <div class="col-sm-2 mb-2">
                <div class="d-grid">
                  <%= submit_tag "Filtrar", :name => nil, class:"btn btn-dark", id:"works_submit", disabled: true %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </nav>
</div>
<div id='works' class="bg-light-custom">
  <br>
  <%= render 'home/results' %>
</div>

sanidart_rails_ver00/app/views/home/index.html.erb
<div id="homepage">
  <div class="container-fluid img-banner">
    <div class="row">
      <div class="col-lg-4 col-xl-3">
        <div class="mb-4" id="profile_area" style="position: sticky; top: 0;">
          <div class="card bg-white text-center mb-4 shadow rounded px-3" id="profile_card">
            <% if @profiles_export.exists? %>
              <div id="card-body" class="card-body">
                <% if @profiles_export[0].image.nil? %>
                  <svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="120" viewBox="0 0 24 24" width="120" class="card-img-top" id="profile_image"><g><rect fill="none" height="24" width="24"/><path d="M21.9,21.9l-8.49-8.49l0,0L3.59,3.59l0,0L2.1,2.1L0.69,3.51L3,5.83V19c0,1.1,0.9,2,2,2h13.17l2.31,2.31L21.9,21.9z M5,18 l3.5-4.5l2.5,3.01L12.17,15l3,3H5z M21,18.17L5.83,3H19c1.1,0,2,0.9,2,2V18.17z"/></g></svg>
                <% else %>
                  <%= image_tag(@profiles_export[0].image, class:"img-thumbnail rounded-circle", size: "120x120", id:"profile_image")%>
                <% end %>
                <h5 class="card-title mt-3 fs-3"><%= @profiles_export[0].name %></h5>
                <p class="card-text text-dark"><%= @profiles_export[0].skills %></p>
                <p class="card-text text-dark mb-4"><i class="bi bi-geo-alt-fill me-1"></i>Belém, PA</p>
                <div class="d-grid gap-2 mb-4">
                  <button type="button" class="btn btn-primary rounded-pill fw-bold"><i class="bi bi-envelope-fill me-2"></i>Mensagem</button>
                  <button type="button" class="btn btn-light text-dark border-secondary rounded-pill fw-bold" onclick="getElementById('works_area').scrollIntoView({block: 'start', behavior: 'smooth'});"><i class="bi bi-grid-1x2-fill me-2"></i>Trabalhos</button>
                </div>
                <div>
                  <% if @profiles_export[0].whatsapp %>
                    <a role="button" class="btn btn-primary rounded-circle m-2" onclick="send_whats()"><i class="bi bi-whatsapp"></i></a>
                  <% else %>
                    <a role="button" class="btn btn-dark rounded-circle disabled m-2"><i class="bi bi-whatsapp"></i></a>
                  <% end %>
                  <% if @profiles_export[0].facebook %>
                    <a role="button" class="btn btn-primary rounded-circle m-2" href="<%= @profiles_export[0].facebook %>" target="_blank"><i class="bi bi-facebook"></i></a>
                  <% else %>
                    <a role="button" class="btn btn-dark rounded-circle disabled m-2"><i class="bi bi-facebook"></i></a>
                  <% end %>
                  <a role="button" class="btn btn-dark rounded-circle disabled m-2"><i class="bi bi-instagram"></i></a>
                  <a role="button" class="btn btn-dark rounded-circle disabled m-2"><i class="bi bi-linkedin"></i></a>
                  <a role="button" class="btn btn-dark rounded-circle disabled m-2"><i class="bi bi-twitter"></i></a>
                  <a role="button" class="btn btn-dark rounded-circle disabled m-2"><i class="bi bi-youtube"></i></a>
                  <a role="button" class="btn btn-dark rounded-circle disabled m-2"><i class="bi bi-telegram"></i></a>
                  <a role="button" class="btn btn-dark rounded-circle disabled m-2"><i class="bi bi-envelope-fill"></i></a>
                </div>
              </div>
            <% else %>
              <img
                src="https://images.unsplash.com/photo-1599272771314-f3ec16bda3f2?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80"
                class="card-img-top" alt="..." id="profile_image">
                <div id="card-body" class="card-body">
                  <h5 class="card-title">C-3PO</h5>
                  <p class="card-text text-muted">Intérprete e relações-sociais. Fluente em 6 milhões de meios de comunicação.</p>
                  <div class="d-grid gap-2">
                    <button type="button" class="btn btn-dark fw-bold"><i class="bi bi-envelope-fill me-2"></i>Enviar Mensagem</button>
                    <button type="button" class="btn btn-dark fw-bold"><i class="bi bi-grid-1x2-fill me-2"></i>Meus Trabalhos</button>
                    <button type="button" class="btn btn-success fw-bold"><i class="bi bi-receipt-cutoff me-2"></i>Solicitar Orçamento</button>
                  </div>
                  <div class="d-grid gap-2">
                    <button type="button" class="btn text-muted fs-5"><i class="bi bi-whatsapp"></i></button>
                    <button type="button" class="btn text-muted fs-5"><i class="bi bi-facebook"></i></button>
                    <button type="button" class="btn text-muted fs-5"><i class="bi bi-instagram"></i></button>
                    <button type="button" class="btn text-muted fs-5"><i class="bi bi-linkedin"></i></button>
                    <button type="button" class="btn text-muted fs-5"><i class="bi bi-twitter"></i></button>
                    <button type="button" class="btn text-muted fs-5"><i class="bi bi-youtube"></i></button>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-lg-8 col-xl-9">
          <%# <div id="pages_margin_top" style="margin-top:25px;"></div> %>
          <svg id="svg_wave" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 25 150 45" preserveAspectRatio="none" shape-rendering="auto">
            <defs>
              <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"></path>
            </defs>
            <g class="parallax">
              <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(255,255,255,0.4)"></use>
              <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.2)"></use>
              <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.1)"></use>
              <use xlink:href="#gentle-wave" x="48" y="7" fill="rgba(255,255,255,0.6)"></use>
              <%# <use xlink:href="#gentle-wave" x="48" y="7" fill="#fff"></use> %>
            </g>
          </svg>
          <% if @pages_export.exists? %>
            <div id="pages_links" class="d-flex justify-content-start bg-white rounded overflow-auto mx-2 pt-1 pb-3" style="-ms-transform: translateY(10px); transform: translateY(10px);">
              <% @pages_export.each do |it| %>
                <button type="button" class="btn btn-outline-dark rounded-pill text-nowrap fw-bold m-2 btn-link-pages" onclick="getElementById('page_<%= it.id %>').scrollIntoView({block: 'start', behavior: 'smooth'});"><%= it.title %></button>
              <% end %>
            </div>
            <% @pages_export.each do |it| %>
              <div class="card border-0 mb-5 bg-light-custom shadow" id="page_<%= it.id %>">
                <div class="card-body pages">
                  <div class="card-text">
                    <div class="ql-editor"><%= it.content %></div>
                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <div class="card border-0 mb-4">
              <img
            src="https://images.unsplash.com/photo-1546435269-527d657231eb?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1416&q=80"
            class="card-img-top" alt="...">
                <div class="card-body">
                  <div class="card-text">
                    O que é Lorem Ipsum?
                    Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos. Lorem Ipsum sobreviveu não só a cinco séculos, como também ao salto para a editoração eletrônica, permanecendo essencialmente inalterado. Se popularizou na década de 60, quando a Letraset lançou decalques contendo passagens de Lorem Ipsum, e mais recentemente quando passou a ser integrado a softwares de editoração eletrônica como Aldus PageMaker.
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <%= render "home/works" %>
      <%= render 'layouts/footer' %>
    </div>
    <script>
    
      if(document.getElementById("profile_area")) {
        document.getElementById("profile_image").addEventListener("load", ()=> {
            var nav_height = document.getElementById("navbar").getBoundingClientRect().height;
            document.getElementById("profile_area").style.top = `${nav_height + 30}px`;
        })          
      }

      function homepage_scroll() {
        if (document.getElementById("homepage")) {
          var nav_height = document.getElementById("navbar").getBoundingClientRect().height;
          // var navbar_space_height = document.getElementById("navbar_space").getBoundingClientRect().height;
          // var total_height = nav_height + navbar_space_height
      
          if (document.getElementById("profile_area").getBoundingClientRect().top <= -nav_height) {
            document.getElementById("profile_image").style.opacity = "0.1";
          } else {
            document.getElementById("profile_image").style.opacity = "1";
          }
        } else {
          window.removeEventListener('scroll', homepage_scroll)
        }
      }
      
      // window.addEventListener('scroll', homepage_scroll)
      
      function send_whats() {
        var uri = "Oi Jaque, tenho interesse nos seus serviços. Podemos conversar?";
        var msg = encodeURI(uri);
        var number = <%= @profiles_export[0].whatsapp %>
        var link = `https://api.whatsapp.com/send/?phone=${number}&text=${msg}`;
        console.log(link)
        window.open(link, "_blank")
      }
      
      function rich_text_replace_terms() {
        var elements = document.querySelectorAll(".pages")
      
        for (var i=0; i < elements.length; i++) {
          elements[i].innerHTML = elements[i].innerHTML.replace(/&lt;/g, "<").replace(/&gt;/g, ">")
        }
      }
      
      rich_text_replace_terms()
    </script>

sanidart_rails_ver00/app/views/home/index.js.erb
document.getElementById('works').innerHTML = '<%=j render 'home/results' %>';